---
- name: Set the Persistant Storage for Halyard
  shell: hal config storage gcs edit --project {{ gcp_project }} --bucket {{ gcs_bucket }} --json-path {{ spinnaker_gcs_key }}

- name: Set the storage source to GCS
  shell: hal config storage edit --type gcs