apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    prometheus:
      enabled: false
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          hpaSpec:
            maxReplicas: 10
            metrics:
            - resource:
                name: cpu
                targetAverageUtilization: 80
              type: Resource
            minReplicas: 3
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          nodeSelector:
            istio: "gateway"
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          service:
            type: "NodePort"
            ports:
            - name: status-port
              port: 15020
              targetPort: 15020
            - name: http2
              port: 80
              targetPort: 80
            - name: https
              port: 443
            - name: kiali
              port: 15029
              targetPort: 15029
            - name: prometheus
              port: 15030
              targetPort: 15030
            - name: grafana
              port: 15031
              targetPort: 15031
            - name: tracing
              port: 15032
              targetPort: 15032
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tcp
              port: 31400
          strategy:
            rollingUpdate:
              maxSurge: 100%
              maxUnavailable: 25%